### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by DaHype** [ddanssaert/home-assistant-ipcamlive#4]
![Scre](https://github.com/ddanssaert/home-assistant-ipcamlive/assets/102579433/26221277-853e-4f4d-b470-18f1197d98a9)

I tried several alias. Also Broadway as in description. No one works :-(

Any idea?

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 13:47:34 (16 occurrences)
Last logged: 13:59:37

Error setting up entry Rhodos_Marina for ipcamlive
Error setting up entry Marina for ipcamlive
Error setting up entry rhodesmarina for ipcamlive
Error setting up entry 5bc8707d9e5c3 for ipcamlive
Error setting up entry broadwaycam for ipcamlive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipcamlive/__init__.py", line 21, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by victordk** [comment]
Any chance of having this fixed?
